{{- /* Create secret */ -}}
{{- if .Values.addons.grafanaAlloy.enabled }}
{{- include "values-secret" (dict "root" $ "package" .Values.addons.grafanaAlloy "name" "grafana-alloy" "defaults" (include "bigbang.defaults.grafana-alloy" .)) }}
{{- end }}

{{- define "bigbang.defaults.grafana-alloy" -}}

image:
  imagePullPolicy: {{ .Values.imagePullPolicy }}

domain: {{ .Values.domain }}

values:
  alloy:
    # -- Security context to apply to the Grafana Alloy container.
    securityContext:
      runAsNonRoot: true
      runAsUser: 1001
      runAsGroup: 1001

    containerSecurityContext:
      capabilities:
        drop:
          - ALL

  configReleoader:
    securityContext:
      runAsNonRoot: true
      runAsUser: 1001
      runAsGroup: 1001

    containerSecurityContext:
      capabilities:
        drop:
          - ALL

  controller:
    securityContext:
      runAsNonRoot: true
      runAsUser: 1001
      runAsGroup: 1001

    containerSecurityContext:
      capabilities:
        drop:
          - ALL

{{- end }}