{{- /* Create secret */ -}}
{{- if .Values.addons.grafanaAlloy.enabled }}
{{- include "values-secret" (dict "root" $ "package" .Values.addons.grafanaAlloy "name" "grafana-alloy" "defaults" (include "bigbang.defaults.grafana-alloy" .)) }}
{{- end }}

{{- define "bigbang.defaults.grafana-alloy" -}}

image:
  imagePullPolicy: {{ .Values.imagePullPolicy }}

domain: {{ .Values.domain }}

global:
  podSecurityContext:
    runAsUser: 473
    runAsGroup: 473
    fsGroup: 473
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
alloy:
    # -- Security context to apply to the Grafana Alloy container.
  securityContext: 
    runAsUser: 473
    runAsGroup: 473
    runAsNonRoot: true
    capabilities:
      drop:
        - ALL

configReleoader:
  securityContext:
    runAsNonRoot: true
    readOnlyRootFilesystem: true
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL

controller:
  securityContext:
    runAsNonRoot: true
    runAsUser: 1001
    runAsGroup: 1001
    capabilities:
      drop:
        - ALL

{{- end }}