{{- if .Values.istio.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: istio-operator
  labels:
    istio-operator-managed: Reconcile
    istio-injection: disabled

{{- if and (ne .Values.registryCredentials.username "") (ne .Values.registryCredentials.password "") }}
---
apiVersion: v1
kind: Secret
metadata:
  name: private-registry
  namespace: istio-operator
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}
{{- end }}