{{- if or .Values.addons.minioOperator.enabled .Values.addons.minio.enabled (and .Values.addons.thanos.enabled (.Values.addons.thanos.values.objstoreConfig | empty) (.Values.addons.thanos.objectStorage.endpoint | empty)) }}
{{- if ( include "imagePullSecret" . ) }}
apiVersion: v1
kind: Secret
metadata:
  name: private-registry
  namespace: minio-operator
  labels:
    app.kubernetes.io/name: minioOperator
    app.kubernetes.io/component: "application-utilities"
    {{- include "commonLabels" . | nindent 4}}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}
{{- end }}
