{{- if or .Values.addons.minioOperator.enabled .Values.addons.minio.enabled (and .Values.addons.thanos.enabled (.Values.addons.thanos.values.objstoreConfig | empty) (.Values.addons.thanos.objectStorage.endpoint | empty)) }}
apiVersion: v1
kind: Namespace
metadata:
  name: minio-operator
  labels:
    istio-injection: enabled
    app.kubernetes.io/name: minioOperator
    app.kubernetes.io/component: "application-utilities"
    {{- include "commonLabels" . | nindent 4}}
{{- end }}
