{{- if .Values.addons.gitlabRunners.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: gitlab-runners

{{- if and (ne .Values.registryCredentials.username "") (ne .Values.registryCredentials.password "") }}
---
apiVersion: v1
kind: Secret
metadata:
  name: private-registry
  namespace: gitlab-runners
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}
{{- end }}