{{- if or .Values.logging.enabled .Values.clusterAuditor.enabled }}
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: eck-operator
  namespace: {{ .Release.Namespace }}
spec:
  targetNamespace: eck-operator
  chart:
    spec:
      chart: {{ .Values.eckoperator.git.path }}
      interval: 5m
      sourceRef:
        kind: GitRepository
        name: eck-operator
        namespace: {{ .Release.Namespace }}

  {{- with .Values.flux }}
  interval: {{ .interval }}
  test:
    enable: false
  install:
    remediation:
      retries: {{ .install.retries }}
  upgrade:
    remediation:
      retries: {{ .upgrade.retries }}
      remediateLastFailure: true
    cleanupOnFail: true
  rollback:
    timeout: {{ .rollback.timeout }}
    cleanupOnFail: {{ .rollback.cleanupOnFail }}
  {{- end }}

  valuesFrom:
    - name: values
      kind: Secret
      valuesKey: "eckoperator.yaml"

  values:
    podAnnotations:
      sidecar.istio.io/inject: "true"
      traffic.sidecar.istio.io/includeInboundPorts: "*"
      traffic.sidecar.istio.io/excludeInboundPorts: "9443"
    imagePullSecrets:
      - name: private-registry

  {{- if .Values.gatekeeper.enabled }}
  dependsOn:
    - name: gatekeeper
      namespace: {{ .Release.Namespace }}
  {{- end }}
{{- end }}