{{- if or .Values.gatekeeper.enabled .Values.clusterAuditor.enabled }}
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gatekeeper
  namespace: {{ .Release.Namespace }}
spec:
  targetNamespace: gatekeeper-system
  chart:
    spec:
      chart: {{ .Values.gatekeeper.git.path }}
      interval: 5m
      sourceRef:
        kind: GitRepository
        name: gatekeeper
        namespace: {{ .Release.Namespace }}

  {{- with .Values.flux }}
  interval: {{ .interval }}
  test:
    enable: false
  install:
    remediation:
      retries: {{ .install.retries }}
  upgrade:
    remediation:
      retries: {{ .upgrade.retries }}
      remediateLastFailure: true
    cleanupOnFail: true
  rollback:
    timeout: {{ .rollback.timeout }}
    cleanupOnFail: {{ .rollback.cleanupOnFail }}
  {{- end }}

  valuesFrom:
    - name: values
      kind: Secret
      valuesKey: "gatekeeper.yaml"

  values:
    image:
      repository: registry1.dso.mil/ironbank/opensource/openpolicyagent/gatekeeper
      release: v3.1.2
    disableValidatingWebhook: true
    createNamespace: false
    imagePullSecrets:
    - name: private-registry
{{- end }}