{{- if or .Values.gatekeeper.enabled .Values.clusterAuditor.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  labels:
    admission.gatekeeper.sh/ignore: no-self-managing
    app: {{ .Release.Name }}-gatekeeper
    control-plane: controller-manager
    gatekeeper.sh/system: "yes"
  name: gatekeeper-system

---
{{- if ( include "imagePullSecret" . ) }}
apiVersion: v1
kind: Secret
metadata:
  name: private-registry
  namespace: gatekeeper-system
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}
{{- end }}