{{- if .Values.twistlock.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: twistlock
---
{{- if ( include "imagePullSecret" . ) }}
apiVersion: v1
kind: Secret
metadata:
  name: private-registry
  namespace: twistlock
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}
{{- end }}