{{- if .Values.addons.sonarqube.enabled }}
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonarqube
  namespace: {{ .Release.Namespace }}
spec:
  releaseName: sonarqube
  targetNamespace: sonarqube
  chart:
    spec:
      chart: {{ .Values.addons.sonarqube.git.path }}
      interval: 5m
      sourceRef:
        kind: GitRepository
        name: sonarqube
        namespace: {{ .Release.Namespace }}

{{- with .Values.flux }}
  interval: {{ .interval }}
  test:
    enable: false
  install:
    remediation:
      retries: {{ .install.retries }}
  upgrade:
    remediation:
      retries: {{ .upgrade.retries }}
      remediateLastFailure: true
    cleanupOnFail: true
  rollback:
    timeout: {{ .rollback.timeout }}
    cleanupOnFail: {{ .rollback.cleanupOnFail }}
  {{- end }}

  valuesFrom:
    - name: values
      kind: Secret
      valuesKey: "sonarqube.yaml"

  values:
    hostname: {{ .Values.hostname }}
    istio:
      enabled: {{ .Values.istio.enabled }}
    monitoring:
      enabled: {{ .Values.monitoring.enabled }}

  {{- if or .Values.gatekeeper.enabled .Values.istio.enabled .Values.monitoring.enabled }}
  dependsOn:
  {{- if .Values.gatekeeper.enabled }}
  - name: gatekeeper
    namespace: {{ .Release.Namespace }}
  {{- end }}
  {{- if .Values.istio.enabled }}
  - name: istio
    namespace: {{ .Release.Namespace }}
  {{- end }}
  {{- if .Values.monitoring.enabled }}
  - name: monitoring
    namespace: {{ .Release.Namespace }}
  {{- end }}
  {{- end }}
{{- end }}
