{{- if .Values.addons.argocd.enabled  }}
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: argocd
  namespace: {{ .Release.Namespace }}
spec:
  interval: {{ .Values.flux.interval }}
  url: {{ .Values.addons.argocd.git.repo }}
  ref:
    {{- include "validRef" .Values.addons.argocd.git | nindent 4 }}
  {{ include "gitIgnore" . }}
  {{- include "gitCreds" .Values.git | nindent 2 }}
{{- end }}
