apiVersion: v1
kind: Secret
metadata:
  name: values
  namespace:  {{ .Release.Namespace }}
type: generic
stringData:
  values.yaml: |
{{ toYaml .Values | indent 4}}
  argocd.yaml: |
{{ toYaml .Values.addons.argocd.values | indent 4 }}
  istiooperator.yaml: |
{{ toYaml .Values.istiooperator.values | indent 4  }}
  authservice.yaml: |
    chains:
    - name: kiali
      client_secret: "{{ .Values.istio.sso.kiali.client_secret }}"
    - name: jaeger
      client_secret: "{{ .Values.istio.sso.jaeger.client_secret }}"
    - name: prometheus
      client_secret: "{{ .Values.monitoring.sso.prometheus.client_secret }}"
    - name: alertmanager
      client_secret: "{{ .Values.monitoring.sso.alertmanager.client_secret }}"
{{ toYaml .Values.addons.authservice.values | indent 4 }}
  istio.yaml: |
{{ toYaml .Values.istio.values | indent 4  }}
  gatekeeper.yaml: |
{{ toYaml .Values.gatekeeper.values | indent 4 }}
  fluentbit.yaml: |
{{ toYaml .Values.fluentbit.values | indent 4 }}
  eckoperator.yaml: |
{{ toYaml .Values.eckoperator.values | indent 4 }}
  logging.yaml: |
{{ toYaml .Values.logging.values | indent 4 }}
  monitoring.yaml: |
    grafana_client_id: {{ .Values.monitoring.sso.grafana.client_id }}
    grafana_client_secret: {{ .Values.monitoring.sso.grafana.client_secret }}
{{ toYaml .Values.monitoring.values | indent 4 }}
  twistlock.yaml: |
{{ toYaml .Values.twistlock.values | indent 4 }} 
  clusterauditor.yaml: |
{{ toYaml .Values.twistlock.values | indent 4 }}
data:
