apiVersion: v1
kind: Secret
metadata:
  name: values
  namespace:  {{ .Release.Namespace }}
type: generic
stringData:
  values.yaml: |
{{ toYaml .Values | indent 4}}
  argocd.yaml: |
{{ toYaml .Values.addons.argocd.values | indent 4 }}
  authservice.yaml: |
{{ toYaml .Values.addons.authservice.values | indent 4 }}
  istio.yaml: |
{{ toYaml .Values.istio.values | indent 4  }}
  gatekeeper.yaml: |
{{ toYaml .Values.gatekeeper.values | indent 4 }}
  logging.yaml: |
{{ toYaml .Values.logging.values | indent 4 }}
  monitoring.yaml: |
{{ toYaml .Values.monitoring.values | indent 4 }}
  twistlock.yaml: |
{{ toYaml .Values.twistlock.values | indent 4 }} 
  clusterauditor.yaml: |
{{ toYaml .Values.twistlock.values | indent 4 }}
data:
