include:
  # "Default" AWS Networking
  - local: '/.gitlab-ci/jobs/networking/aws/.gitlab-ci.yml'

  # Clusters in CI
  - local: '/.gitlab-ci/jobs/ci-cluster/.gitlab-ci.yml'

  # RKE2 Gitlab CI jobs
  - local: '/.gitlab-ci/jobs/rke2/.gitlab-ci.yml'

.terraformer:
  image:
    name: registry.dso.mil/platform-one/big-bang/pipeline-templates/pipeline-templates/terraform:0.13.5
    entrypoint:
      - /usr/bin/env
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
  interruptible: false
  variables:
    TF_IN_AUTOMATION: "1"
    TF_VAR_ci_pipeline_url: $CI_PIPELINE_URL
  before_script:
    - echo -e "\e[0Ksection_start:`date +%s`:terraform_init[collapsed=true]\r\e[0KTerraform Init"
    - echo "$TF_VAR_env"
    - cd ${CI_PROJECT_DIR}/${TF_ROOT}
    - terraform version
    - terraform init -input=false
    - terraform workspace select $TF_VAR_env || terraform workspace new $TF_VAR_env
    - terraform validate
    - echo -e "\e[0Ksection_end:`date +%s`:terraform_init\r\e[0K"

.terraform destroy workspace:
  after_script:
    - echo -e "\e[0Ksection_start:`date +%s`:terraform_destroy_workspace[collapsed=true]\r\e[0KTerraform Destroy Workspace"
    - cd ${CI_PROJECT_DIR}/${TF_ROOT}
    - terraform workspace select default && terraform workspace delete "${TF_VAR_env}"
    - echo -e "\e[0Ksection_end:`date +%s`:terraform_destroy_workspace\r\e[0K"
