{{- if and .Values.istio.enabled .Values.addons.authservice.enabled }}
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authservice
  namespace: {{ .Release.Namespace }}
spec:
  targetNamespace: istio-system
  chart:
    spec:
      chart: {{ .Values.addons.authservice.git.path }}
      interval: 5m
      sourceRef:
        kind: GitRepository
        name: authservice
        namespace: {{ .Release.Namespace }}

  {{- with .Values.flux }}
  interval: {{ .interval }}
  test:
    enable: false
  install:
    remediation:
      retries: {{ .install.retries }}
  upgrade:
    remediation:
      retries: {{ .upgrade.retries }}
      remediateLastFailure: true
    cleanupOnFail: true
  rollback:
    timeout: {{ .rollback.timeout }}
    cleanupOnFail: {{ .rollback.cleanupOnFail }}
  {{- end }}

  valuesFrom:
    - name: values
      kind: Secret
      valuesKey: "authservice.yaml"
  values:
    imagePullSecrets:
      - name: private-registry
    global:
      oidc:
        host: {{ .Values.sso.oidc.host }}
        realm: {{ .Values.sso.oidc.realm }}
      jwks: {{ .Values.sso.jwks }}
      client_id: {{ .Values.sso.client_id }}
      client_secret: {{ .Values.sso.client_secret }}
      certificate_authority: {{ .Values.sso.certificate_authority }}
    chains:
      kiali:
        match:
          header: ":authority"
          prefix: "kiali"
        client_id: {{ .Values.istio.sso.kiali.client_id }}
        client_secret: "{{ .Values.istio.sso.kiali.client_secret }}"
        callback_uri: https://kiali.{{ .Values.hostname }}/login
      jaeger:
        match:
          header: ":authority"
          prefix: "tracing"
        client_id: "{{ .Values.istio.sso.jaeger.client_id }}"
        client_secret: "{{ .Values.istio.sso.jaeger.client_secret }}"
        callback_uri: https://tracing.{{ .Values.hostname }}/login
    filterLabel: keycloak
  dependsOn:
  - name: istio
    namespace: {{ .Release.Namespace }}
{{- end }}