{{- if .Values.addons.gitlab.enabled }}
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitlab
  namespace: {{ .Release.Namespace }}
spec:
  releaseName: gitlab
  targetNamespace: gitlab
  chart:
    spec:
      chart: {{ .Values.addons.gitlab.git.path }}
      interval: 5m
      sourceRef:
        kind: GitRepository
        name: gitlab
        namespace: {{ .Release.Namespace }}
  timeout: 10m
{{- with .Values.flux }}
  interval: {{ .interval }}
  test:
    enable: false
  install:
    remediation:
      retries: {{ .install.retries }}
  upgrade:
    remediation:
      retries: {{ .upgrade.retries }}
      remediateLastFailure: true
    cleanupOnFail: true
  rollback:
    timeout: {{ .rollback.timeout }}
    cleanupOnFail: {{ .rollback.cleanupOnFail }}
  {{- end }}

  valuesFrom:
    - name: values
      kind: Secret
      valuesKey: "gitlab.yaml"

  values:
    hostname: {{ .Values.hostname }}
    istio:
      enabled: {{ .Values.istio.enabled }}
    monitoring:
      enabled: {{ .Values.monitoring.enabled }}
    {{- if .Values.addons.gitlab.database.host }}
    postgresql:
      install: false
    {{- end }}
    redis:
      metrics:
        image:
          pullSecrets: 
          - private-registry
      image:
        pullSecrets: 
        - private-registry
    registry:
      {{- if .Values.addons.gitlab.objectstorage.endpoint }}
      storage:
        secret: gitlab-object-storage
        key: registry
      {{- end }}
      image:
        pullSecrets:
        - name: private-registry
    shared-secrets:
      selfsign:
        image:
          pullSecrets:
          - name: private-registry
    gitlab:
      task-runner:
        {{- if .Values.addons.gitlab.objectstorage.endpoint }}
        backups:
          objectStorage:
            config:
              secret: gitlab-object-storage
              key: backups
        {{- end }}
        image:
          pullSecrets:
          - name: private-registry
      migrations:
        image:
          pullSecrets:
          - name: private-registry
      webservice:
        image:
          pullSecrets:
          - name: private-registry 
        workhorse:
          pullSecrets:
          - name: private-registry 
      sidekiq:
        image:
          pullSecrets:
          - name: private-registry
      gitaly:
        image:
          pullSecrets:
          - name: private-registry
      gitlab-shell:
        image:
          pullSecrets:
          - name: private-registry
      gitlab-exporter:
        image:
          pullSecrets:
          - name: private-registry
    minio:
      pullSecrets:
      - name: private-registry
    global:
      hosts:
        domain: {{ .Values.hostname }}
        gitlab:
          name: {{ .Values.addons.gitlab.hostnames.gitlab }} 
        registry:
          name: {{ .Values.addons.gitlab.hostnames.registry }}
      {{- if .Values.addons.gitlab.objectstorage.endpoint }}
      minio:
        enabled: false
      {{- end }}
      {{- if .Values.addons.gitlab.database.host }}
      psql:
        host: {{ .Values.addons.gitlab.database.host }}
        port: {{ .Values.addons.gitlab.database.port }}
        username: {{ .Values.addons.gitlab.database.username }}
        database: {{ .Values.addons.gitlab.database.database }}
        password:
          secret: gitlab-database
          key: PGPASSWORD
      {{- end }}
      {{- if .Values.addons.gitlab.objectstorage.endpoint }}
      registry:
        {{- if .Values.addons.gitlab.objectstorage.bucketPrefix }}
        bucket: {{ .Values.addons.gitlab.objectstorage.bucketPrefix }}-gitlab-registry
        {{- else }}
        bucket: gitlab-registry
        {{- end }}
      {{- end }}
      {{- if or .Values.addons.gitlab.sso.enabled .Values.addons.gitlab.objectstorage.endpoint }}
      appConfig:
      {{- end }}
        {{- if .Values.addons.gitlab.sso.enabled }}
        omniauth:
          enabled: true
          {{- $global := .Values.addons.gitlab.values.global | default dict }}
          {{- $appConfig := $global.appConfig | default dict }}
          {{- $omniauth := $appConfig.omniauth | default dict }}
          {{- if hasKey $omniauth "allowSingleSignOn" }}
          allowSingleSignOn: {{ .Values.addons.gitlab.values.global.appConfig.omniauth.allowSingleSignOn }}
          {{- else }}
          allowSingleSignOn: ['openid_connect']
          {{- end }}
          {{- if hasKey $omniauth "blockAutoCreatedUsers" }}
          blockAutoCreatedUsers: {{ .Values.addons.gitlab.values.global.appConfig.omniauth.blockAutoCreatedUsers }}
          {{- else }}
          blockAutoCreatedUsers: false
          {{- end }}
          providers:
              - secret: gitlab-sso-provider
                key: gitlab-sso.json
        {{- end }}
        {{- if .Values.addons.gitlab.objectstorage.endpoint }}
        lfs:
          {{- if .Values.addons.gitlab.objectstorage.bucketPrefix }}
          bucket: {{ .Values.addons.gitlab.objectstorage.bucketPrefix }}-gitlab-lfs
          {{- else }}
          bucket: gitlab-lfs
          {{- end }}
          connection:
            secret: gitlab-object-storage
            key: rails
        artifacts:
          {{- if .Values.addons.gitlab.objectstorage.bucketPrefix }}
          bucket: {{ .Values.addons.gitlab.objectstorage.bucketPrefix }}-gitlab-artifacts
          {{- else }}
          bucket: gitlab-artifacts
          {{- end }}
          connection:
            secret: gitlab-object-storage
            key: rails
        uploads:
          {{- if .Values.addons.gitlab.objectstorage.bucketPrefix }}
          bucket: {{ .Values.addons.gitlab.objectstorage.bucketPrefix }}-gitlab-uploads
          {{- else }}
          bucket: gitlab-uploads
          {{- end }}
          connection:
            secret: gitlab-object-storage
            key: rails
        packages:
          {{- if .Values.addons.gitlab.objectstorage.bucketPrefix }}
          bucket: {{ .Values.addons.gitlab.objectstorage.bucketPrefix }}-gitlab-packages
          {{- else }}
          bucket: gitlab-packages
          {{- end }}
          connection:
            secret: gitlab-object-storage
            key: rails
        externalDiffs:
          {{- if .Values.addons.gitlab.objectstorage.bucketPrefix }}
          bucket: {{ .Values.addons.gitlab.objectstorage.bucketPrefix }}-gitlab-mr-diffs
          {{- else }}
          bucket: gitlab-mr-diffs
          {{- end }}
          connection:
            secret: gitlab-object-storage
            key: rails
        terraformState:
          {{- if .Values.addons.gitlab.objectstorage.bucketPrefix }}
          bucket: {{ .Values.addons.gitlab.objectstorage.bucketPrefix }}-gitlab-terraform-state
          {{- else }}
          bucket: gitlab-terraform-state
          {{- end }}
          connection:
            secret: gitlab-object-storage
            key: rails
        dependencyProxy:
          {{- if .Values.addons.gitlab.objectstorage.bucketPrefix }}
          bucket: {{ .Values.addons.gitlab.objectstorage.bucketPrefix }}-gitlab-dependency-proxy
          {{- else }}
          bucket: gitlab-dependency-proxy
          {{- end }}
          connection: 
            secret: gitlab-object-storage
            key: rails
        pseudonymizer:
          {{- if .Values.addons.gitlab.objectstorage.bucketPrefix }}
          bucket: {{ .Values.addons.gitlab.objectstorage.bucketPrefix }}-gitlab-pseudo
          {{- else }}
          bucket: gitlab-pseudo
          {{- end }}
          connection:
            secret: gitlab-object-storage
            key: rails
        backups:
          {{- if .Values.addons.gitlab.objectstorage.bucketPrefix }}
          bucket: {{ .Values.addons.gitlab.objectstorage.bucketPrefix }}-gitlab-backup
          {{- else }}
          bucket: gitlab-backup
          {{- end }}
          {{- if .Values.addons.gitlab.objectstorage.bucketPrefix }}
          tmpBucket: {{ .Values.addons.gitlab.objectstorage.bucketPrefix }}-gitlab-backup-tmp
          {{- else }}
          tmpBucket: gitlab-backup-tmp
          {{- end }}
        {{- end }}
      certificates:
        image:
          pullSecrets:
          - name: private-registry
      kubectl:
        image:
          pullSecrets:
          - name: private-registry

  {{- if or .Values.gatekeeper.enabled .Values.istio.enabled .Values.monitoring.enabled }}
  dependsOn:
  {{- if .Values.gatekeeper.enabled }}
  - name: gatekeeper
    namespace: {{ .Release.Namespace }}
  {{- end }}
  {{- if .Values.istio.enabled }}
  - name: istio
    namespace: {{ .Release.Namespace }}
  {{- end }}
  {{- if .Values.monitoring.enabled }}
  - name: monitoring
    namespace: {{ .Release.Namespace }}
  {{- end }}
  {{- end }}
{{- end }}