{{- if .Values.addons.gitlab.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  labels:
    app: gitlab
  name: gitlab

---
{{- if and (ne .Values.registryCredentials.username "") (ne .Values.registryCredentials.password "") }}
apiVersion: v1
kind: Secret
metadata:
  name: private-registry
  namespace: gitlab
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}
{{- end }}