{{- if .Values.addons.gitlab.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  labels:
    app: gitlab
  name: gitlab
---
{{- if ( include "imagePullSecret" . ) }}
apiVersion: v1
kind: Secret
metadata:
  name: private-registry
  namespace: gitlab
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}
{{- end }}