apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bigbang
spec:
  # Increase reconciliation interval for dev
  interval: 1m0s
  values:
    hostname: bigbang.dev

    # Tune flux for dev
    flux:
      interval: 1m
      rollback:
        cleanupOnFail: false

    # clusterAuditor:

#    monitoring:

    logging:
      # Directly modify chart values for dev workloads
      values:
        elasticsearch:
          master:
            count: 1
            persistence:
              size: 5Gi
            resources:
              limits:
                cpu: 1
                memory: 2Gi
          data:
            count: 1
            persistence:
              size: 5Gi
            resources:
              limits:
                cpu: 1
                memory: 2Gi

    istio:
      # Directly modify chart values for dev workloads
      values:
        kiali:
          dashboard:
            auth:
              strategy: "anonymous"   

    gatekeeper:
      # Directly modify chart values for dev workloads
      values:
        replicas: 1

    twistlock:
      # Directly modify chart values for dev workloads
      values:
        console:
          persistence:
            size: 5Gi
