{{- if .Values.addons.minio.enabled }}
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio
  namespace: {{ .Release.Namespace }}
spec:
  targetNamespace: minio
  chart:
    spec:
      chart: {{ .Values.addons.minio.minioinstance.git.path }}
      interval: 5m
      sourceRef:
        kind: GitRepository
        name: minio
        namespace: {{ .Release.Namespace }}

  {{- with .Values.flux }}
  interval: {{ .interval }}
  test:
    enable: false
  install:
    remediation:
      retries: {{ .install.retries }}
  upgrade:
    remediation:
      retries: {{ .upgrade.retries }}
      remediateLastFailure: true
    cleanupOnFail: true
  rollback:
    timeout: {{ .rollback.timeout }}
    cleanupOnFail: {{ .rollback.cleanupOnFail }}
  {{- end }}

  valuesFrom:
    - name: values
      kind: Secret
      valuesKey: "minio.yaml"

  values:
    podAnnotations:
      sidecar.istio.io/inject: "true"
      traffic.sidecar.istio.io/includeInboundPorts: "*"
      traffic.sidecar.istio.io/excludeInboundPorts: "9443"
    imagePullSecrets:
      - name: private-registry

  dependsOn:
  {{- if  .Values.gatekeeper.enabled }}
    - name: gatekeeper
      namespace: {{ .Release.Namespace }}
  {{- end }}

  {{- if .Values.istio.enabled }}
    - name: istio
      namespace: {{ .Release.Namespace }}
  {{- end }}

    - name: minio-operator
      namespace: {{ .Release.Namespace }}
{{- end }}
