{{- if .Values.addons.minio.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: minio

---
{{- if and (ne .Values.registryCredentials.username "") (ne .Values.registryCredentials.password "") }}
apiVersion: v1
kind: Secret
metadata:
  name: private-registry
  namespace: minio
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}
{{- end }}