{{- if and (not .Values.offline) .Values.istio.enabled .Values.istiocni.enabled .Values.global.openshift }}
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: istio-cni
  namespace: {{ .Release.Namespace }}
spec:
  interval: {{ .Values.flux.interval }}
  url: {{ .Values.istiocni.git.repo }}
  ref:
    {{- include "validRef" .Values.istiocni.git | nindent 4 }}
  {{ include "gitIgnore" . }}
  {{- include "gitCreds" .Values.git | nindent 2 }}
{{- end }}