.rke2 tf:
  extends: .terraformer
  variables:
    TF_ROOT: ".gitlab-ci/jobs/rke2/dependencies/terraform/env/ci"

.rke2 tf airgap:
  extends: .rke2 tf
  variables:
    TF_ROOT: ".gitlab-ci/jobs/rke2/dependencies/terraform/env/ci-airgap"

.rke2 up:
  extends: .rke2 tf
  script:
    # Fetch dependencies
    - apk add bash aws-cli

    - terraform apply -input=false -auto-approve
    - VPC_CIDR=`terraform output vpc_cidr`
    - sed -i "s#VPC_CIDR#$VPC_CIDR#g" ${CI_PROJECT_DIR}/.gitlab-ci/jobs/rke2/dependencies/k8s-resources/default-proxy-env.yaml
    - UTILITY_IP=`terraform output utility_ip`
    - sed -i "s/PROXY_IP/$UTILITY_IP/g" ${CI_PROJECT_DIR}/.gitlab-ci/jobs/rke2/dependencies/k8s-resources/default-proxy-istio.yaml
    - mv ${CI_PROJECT_DIR}/.gitlab-ci/jobs/rke2/dependencies/k8s-resources/default-proxy-* ${CI_PROJECT_DIR}
    - mv rke2.yaml ${CI_PROJECT_DIR}/rke2.yaml
  artifacts:
    paths:
      - ${CI_PROJECT_DIR}/rke2.yaml
      - ${CI_PROJECT_DIR}/default-proxy-env.yaml
      - ${CI_PROJECT_DIR}/default-proxy-istio.yaml

.rke2 airgap up:
  extends: 
    - .rke2 up
    - .rke2 tf airgap

.rke2 down:
  extends:
    - .rke2 tf
    - .terraform destroy workspace
  script:
    - terraform destroy -input=false -auto-approve

.rke2 airgap down:
  extends: 
    - .rke2 down
    - .rke2 tf airgap
