.rke2 tf:
  extends: .terraformer
  variables:
    TF_ROOT: ".gitlab-ci/jobs/rke2/dependencies/terraform/env/ci"

.rke2 up:
  extends: .rke2 tf
  script:
    - echo -e "\e[0Ksection_start:`date +%s`:rke2_up[collapsed=true]\r\e[0K\e[33;1mRKE2 Up\e[37m"
    # Fetch dependencies
    - apk add bash aws-cli
    - terraform apply -input=false -auto-approve
    - mv rke2.yaml ${CI_PROJECT_DIR}/rke2.yaml
    - echo -e "\e[0Ksection_end:`date +%s`:rke2_up\r\e[0K"
  artifacts:
    paths:
      - ${CI_PROJECT_DIR}/rke2.yaml

.rke2 down:
  extends:
    - .rke2 tf
    - .terraform destroy workspace
  script:
    - echo -e "\e[0Ksection_start:`date +%s`:rke2_down[collapsed=true]\r\e[0K\e[33;1mRKE2 Down\e[37m"
    - terraform destroy -input=false -auto-approve
    - echo -e "\e[0Ksection_end:`date +%s`:rke2_down\r\e[0K"
