{{- if .Values.istioBase.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: istio-base
  labels:
    istio-base-managed: Reconcile
    istio-injection: disabled
    app.kubernetes.io/name: istio-base
    app.kubernetes.io/component: "core"
    {{- include "commonLabels" . | nindent 4}}
{{- end }}