{{- if .Values.istioBase.enabled }}
{{- include "values-secret" (dict "root" $ "package" .Values.istioBase "name" "istio-base" "defaults" (include "bigbang.defaults.istioBase" .)) }}
{{- end }}

{{- define "bigbang.defaults.istioBase" -}}
createNamespace: false

enterprise: {{ .Values.istio.enterprise }}
imagePullPolicy: {{ .Values.imagePullPolicy }}

imagePullSecrets:
  - private-registry

networkPolicies:
  enabled: {{ .Values.networkPolicies.enabled }}
  controlPlaneCidr: {{ .Values.networkPolicies.controlPlaneCidr }}
monitoring:
  enabled: {{ .Values.monitoring.enabled }}
{{- end -}}
