{{- if .Values.addons.anchore.enabled }}
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: anchore
  namespace: {{ .Release.Namespace }}
spec:
  releaseName: anchore
  targetNamespace: anchore
  chart:
    spec:
      chart: {{ .Values.addons.anchore.git.path }}
      interval: 5m
      sourceRef:
        kind: GitRepository
        name: anchore
        namespace: {{ .Release.Namespace }}

  {{- with .Values.flux }}
  timeout: {{ .Values.addons.anchore.flux.timeout | default .timeout }}
  interval: {{ .Values.addons.anchore.flux.interval | default .interval }}
  test:
    enable: {{ .Values.addons.anchore.flux.test.enabled | default false }}
    ignoreFailures: {{ .Values.addons.anchore.flux.test.ignoreFailures | default false }}
  install:
    disableWait: {{ .Values.addons.anchore.flux.install.disableWait | default false }}
    skipCRDs: {{ .Values.addons.anchore.flux.install.skipCRDs | default false }}
    remediation:
      retries: {{ .Values.addons.anchore.flux.install.retries | default .install.retries }}
  upgrade:
    disableWait: {{ .Values.addons.anchore.flux.upgrade.disableWait | default true }}
    force: {{ .Values.addons.anchore.flux.upgrade.force | default false }}
    remediation:
      retries: {{ .Values.addons.anchore.flux.upgrade.retries | default .upgrade.retries }}
      remediateLastFailure: {{ .Values.addons.anchore.flux.upgrade.remediation.remediateLastFailure | default true }}
    cleanupOnFail: {{ .Values.addons.anchore.flux.upgrade.cleanupOnFail | default true }}
  rollback:
    disableWait: {{ .Values.addons.anchore.flux.rollback.disableWait | default false }}
    timeout: {{ .Values.addons.anchore.flux.rollback.timeout | default .rollback.timeout }}
    force: {{ .Values.addons.anchore.flux.rollback.force | default false }}
    recreate: {{ .Values.addons.anchore.flux.rollback.recreate | default false }}
    cleanupOnFail: {{ .Values.addons.anchore.flux.rollback.cleanupOnFail | default .rollback.cleanupOnFail }}
  {{- end }}

  valuesFrom:
    - name: {{ .Release.Name }}-anchore-values
      kind: Secret
      valuesKey: "common"
    - name: {{ .Release.Name }}-anchore-values
      kind: Secret
      valuesKey: "defaults"
    - name: {{ .Release.Name }}-anchore-values
      kind: Secret
      valuesKey: "overlays"

  {{- if or .Values.istio.enabled .Values.monitoring.enabled }}
  dependsOn:
    {{- if .Values.istio.enabled }}
    - name: istio
      namespace: {{ .Release.Namespace }}
    {{- end }}
    {{- if .Values.monitoring.enabled }}
    - name: monitoring
      namespace: {{ .Release.Namespace }}
    {{- end }}
  {{- end }}
{{- end }}
