{{- if .Values.addons.anchore.enabled }}
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: anchore
  namespace: {{ .Release.Namespace }}
spec:
  releaseName: anchore
  targetNamespace: anchore
  chart:
    spec:
      chart: {{ .Values.addons.anchore.git.path }}
      interval: 5m
      sourceRef:
        kind: GitRepository
        name: anchore
        namespace: {{ .Release.Namespace }}

  {{- with .Values.flux }}
  interval: {{ .interval }}
  test:
    enable: false
  install:
    remediation:
      retries: {{ .install.retries }}
  upgrade:
    remediation:
      retries: {{ .upgrade.retries }}
      remediateLastFailure: true
    cleanupOnFail: true
  rollback:
    timeout: {{ .rollback.timeout }}
    cleanupOnFail: {{ .rollback.cleanupOnFail }}
  {{- end }}

  valuesFrom:
    - name: values
      kind: Secret
      valuesKey: "anchore.yaml"
  values:
    hostname: {{ .Values.hostname }}
    istio:
      enabled: {{ .Values.istio.enabled }}
    {{- if .Values.addons.anchore.enterprise.licenseYaml }}
    enterpriseLicense:
      b64encYaml: {{ .Values.addons.anchore.enterprise.licenseYaml | b64enc }}
    {{- else if .Values.addons.anchore.enterprise.b64encLicenseYaml }}
    enterpriseLicense:
      b64encYaml: {{ .Values.addons.anchore.enterprise.b64encLicenseYaml }}
    {{- end }}
    {{- if .Values.addons.anchore.enterprise.enabled }}
    sso:
      enabled: {{ .Values.addons.anchore.sso.enabled }}
      spEntityId: {{ .Values.addons.anchore.sso.clientId }}
      acsUrl: "https://anchore.{{ .Values.hostname }}/service/sso/auth/keycloak"
      idpMetadataUrl: {{ .Values.addons.anchore.sso.samlDescriptorUrl }}
      roleAttribute: {{ .Values.addons.anchore.sso.roleAttribute }}
    {{- end }}
    anchoreEnterpriseGlobal:
      enabled: {{ .Values.addons.anchore.enterprise.enabled }}
      imagePullSecretName: private-registry
    postgresql:
      imagePullSecrets: private-registry
      enabled: {{ .Values.addons.anchore.postgresql.enabled }}
      {{- if .Values.addons.anchore.postgresql.user }}
      postgresUser: {{ .Values.addons.anchore.postgresql.user }}
      {{- end }}
      {{- if .Values.addons.anchore.postgresql.password }}
      postgresPassword: {{ .Values.addons.anchore.postgresql.password }}
      {{- end }}
      {{- if .Values.addons.anchore.postgresql.mainDB }}
      postgresDatabase: {{ .Values.addons.anchore.postgresql.mainDB }}
      {{- end }}
      {{- if .Values.addons.anchore.postgresql.endpoint }}
      externalEndpoint: {{ .Values.addons.anchore.postgresql.endpoint }}
      {{- end }}
    anchoreGlobal:
      defaultAdminPassword: {{ .Values.addons.anchore.adminPassword }}
      imagePullSecretName: private-registry
      enableMetrics: {{ .Values.monitoring.enabled }}
      metricsAuthDisabled: {{ .Values.monitoring.enabled }}
      {{- if .Values.addons.anchore.enterprise.enabled }}
      oauthEnabled: {{ .Values.addons.anchore.sso.enabled }}
      hashedPasswords: {{ .Values.addons.anchore.sso.enabled }}
      {{- end }}
    {{- if .Values.addons.anchore.enterprise.enabled }}
    anchore-feeds-db:
      imagePullSecrets: private-registry
      enabled: {{ .Values.addons.anchore.postgresql.enabled }}
      {{- if .Values.addons.anchore.postgresql.user }}
      postgresUser: {{ .Values.addons.anchore.postgresql.user }}
      {{- end }}
      {{- if .Values.addons.anchore.postgresql.password }}
      postgresPassword: {{ .Values.addons.anchore.postgresql.password }}
      {{- end }}
      {{- if .Values.addons.anchore.postgresql.enterpriseFeedsDB }}
      postgresDatabase: {{ .Values.addons.anchore.postgresql.enterpriseFeedsDB }}
      {{- end }}
      {{- if .Values.addons.anchore.postgresql.endpoint }}
      externalEndpoint: {{ .Values.addons.anchore.postgresql.endpoint }}
      {{- end }}
    anchoreEnterpriseUi:
      imagePullSecretName: private-registry
    anchore-ui-redis:
      enabled: {{ .Values.addons.anchore.enterpriseUiRedis.enabled }}
      externalEndpoint: "redis://:{{ .Values.addons.anchore.enterpriseUiRedis.password }}@{{ .Values.addons.anchore.enterpriseUiRedis.endpoint }}"
      {{- if .Values.addons.anchore.enterpriseUiRedis.password }}
      password: {{ .Values.addons.anchore.enterpriseUiRedis.password }}
      {{- end }}
      image:
        pullSecrets:
        - private-registry
    {{- end }}

  {{- if or .Values.istio.enabled .Values.monitoring.enabled }}
  dependsOn:
    {{- if .Values.istio.enabled }}
    - name: istio
      namespace: {{ .Release.Namespace }}
    {{- end }}
    {{- if .Values.monitoring.enabled }}
    - name: monitoring
      namespace: {{ .Release.Namespace }}
    {{- end }}
  {{- end }}
{{- end }}
