{{- if .Values.addons.anchore.enabled }}
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: anchore
  namespace: {{ .Release.Namespace }}
spec:
  targetNamespace: anchore
  chart:
    spec:
      chart: {{ .Values.addons.anchore.git.path }}
      interval: 5m
      sourceRef:
        kind: GitRepository
        name: anchore
        namespace: {{ .Release.Namespace }}

  {{- with .Values.flux }}
  interval: {{ .interval }}
  test:
    enable: false
  install:
    remediation:
      retries: {{ .install.retries }}
  upgrade:
    remediation:
      retries: {{ .upgrade.retries }}
      remediateLastFailure: true
    cleanupOnFail: true
  rollback:
    timeout: {{ .rollback.timeout }}
    cleanupOnFail: {{ .rollback.cleanupOnFail }}
  {{- end }}

  valuesFrom:
    - name: values
      kind: Secret
      valuesKey: "anchore.yaml"
  values:
    hostname: {{ .Values.hostname }}
    istio:
      enabled: {{ .Values.istio.enabled }}
    postgresql:
      imagePullSecrets: private-registry
    anchoreGlobal:
      imagePullSecretName: private-registry
    anchoreEnterpriseGlobal:
      imagePullSecretName: private-registry
    anchore-feeds-db:
      imagePullSecrets: private-registry
    anchoreEnterpriseUi:
      imagePullSecretName: private-registry
    anchore-ui-redis:
      image:
        pullSecrets:
        - private-registry

  {{- if .Values.istio.enabled }}
  dependsOn:
  - name: istio
    namespace: {{ .Release.Namespace}}
  {{- end }}
{{- end }}
