{{- if .Values.monitoring.enabled }}
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: monitoring
  namespace: {{ .Release.Namespace }}
spec:
  targetNamespace: monitoring
  chart:
    spec:
      chart: {{ .Values.monitoring.git.path }}
      interval: 5m
      sourceRef:
        kind: GitRepository
        name: monitoring
        namespace: {{ .Release.Namespace }}

  {{- with .Values.flux }}
  interval: {{ .interval }}
  test:
    enable: false
  install:
    remediation:
      retries: {{ .install.retries }}
  upgrade:
    remediation:
      retries: {{ .upgrade.retries }}
      remediateLastFailure: true
    cleanupOnFail: true
  rollback:
    timeout: {{ .rollback.timeout }}
    cleanupOnFail: {{ .rollback.cleanupOnFail }}
  {{- end }}

  valuesFrom:
    - name: values
      kind: Secret
      valuesKey: "monitoring.yaml"

  values:
    hostname: {{ .Values.hostname }}
    istio:
      enabled: {{ .Values.istio.enabled }}
    global:
      imagePullSecrets:
        - name: private-registry
    grafana:
      image:
        pullSecrets:
        - private-registry
    prometheus-node-exporter:
      serviceAccount:
        imagePullSecrets:
        - name: private-registry
    kube-state-metrics:
      imagePullSecrets:
      - name: private-registry

  # TODO: DRY this up
  {{- if or .Values.gatekeeper.enabled .Values.istio.enabled }}
  dependsOn:
  {{- if .Values.istio.enabled }}
    - name: istio
      namespace: {{ .Release.Namespace }}
  {{- end }}
  {{- if .Values.gatekeeper.enabled }}
    - name: gatekeeper
      namespace: {{ .Release.Namespace }}
  {{- end }}
  {{- end }}
{{- end }}