{{- if .Values.airflow.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  labels:
    app: {{ .Release.Name }}-airflow
  name: airflow
---
apiVersion: v1
kind: Secret
metadata:
  name: appsrepo
  namespace: flux-system
type: opaque
data:
   .dockerconfigjson: eyAiYXV0aHMiOiB7ICJodHRwczovL3JlZ2lzdHJ5LmlsMi5kc29wLmlvIjogeyJhdXRoIjogImJXRjBkQzUyWVhOeGRXVjZPbEYxTFhSdUxUaHhhM1JYT0hOdFJEWm1hRzloIiB9IH0gfQo=
   password: UXUtdG4tOHFrdFc4c21ENmZob2E=
   username: bWF0dC52YXNxdWV6
