{{- if .Values.airflow.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  labels:
    app: {{ .Release.Name }}-airflow
  name: airflow
---
apiVersion: v1
kind: Secret
metadata:
  name: appsrepo
  namespace: bigbang
type: opaque
data:
  password: UXUtdG4tOHFrdFc4c21ENmZob2E=
  username: bWF0dC52YXNxdWV6
{{- end }}