apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: flux-system

resources:
- ../../base/flux/

patches:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: helm-controller
  path: patches/helm-controller-patch.yaml
