{{- if .Values.istio.enabled }}
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio
  namespace: {{ .Release.Namespace }}
spec:
  targetNamespace: istio-system
  chart:
    spec:
      chart: {{ .Values.istio.git.path }}
      interval: 5m
      sourceRef:
        kind: GitRepository
        name: istio-controlplane
        namespace: {{ .Release.Namespace }}

  {{- with .Values.flux }}
  interval: {{ .interval }}
  test:
    enable: false
  install:
    remediation:
      retries: {{ .install.retries }}
  upgrade:
    remediation:
      retries: {{ .upgrade.retries }}
      remediateLastFailure: true
    cleanupOnFail: true
  rollback:
    timeout: {{ .rollback.timeout }}
    cleanupOnFail: {{ .rollback.cleanupOnFail }}
  {{- end }}

  valuesFrom:
    - name: values
      kind: Secret
      valuesKey: "istio.yaml"
  values:
    hostname: {{ .Values.hostname }}

    imagePullSecrets:
      - private-registry

  dependsOn:
    - name: istio-operator
      namespace: {{ .Release.Namespace }}

    {{- if .Values.gatekeeper.enabled }}
    - name: gatekeeper
      namespace: {{ .Release.Namespace }}
    {{- end }}
{{- end }}