{{- if .Values.istio.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
{{- if ( include "imagePullSecret" . ) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: private-registry
  namespace: istio-system
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}
{{- end }}