apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: proxy
spec:
  hosts:
  - proxy.dsop.io # ignored
  addresses:
  - PROXY_IP/32
  ports:
  - number: 8888
    name: tcp
    protocol: TCP
  location: MESH_EXTERNAL