apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bigbang
spec:
  targetNamespace: bigbang
  releaseName: bigbang
  interval: 10m
  chart:
    spec:
      chart: chart
      sourceRef:
        kind: GitRepository
        name: bigbang
  test:
    enable: false
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
      remediateLastFailure: true
    cleanupOnFail: true
  rollback:
    timeout: 10m
    cleanupOnFail: false
  valuesFrom:
    - kind: Secret
      name: common-bb
    - kind: ConfigMap
      name: common
    - kind: Secret
      name: environment-bb
    - kind: ConfigMap
      name: environment