configurations:
- transformer.yaml

namespace: bigbang

commonLabels:
  owner: bigbang

resources:
  - namespace.yaml
  - gitrepository.yaml
  - helmrelease.yaml

configMapGenerator:
  - name: common
    behavior: create
    literals:
    - values.yaml=
  - name: environment
    behavior: create
    literals:
    - values.yaml=

secretGenerator:
  - name: common
    behavior: create
    literals:
    - values.yaml=
  - name: environment
    behavior: create
    literals:
    - values.yaml=