kind: ZarfPackageConfig
metadata:
  name: big-bang
  description: "Deploy Big Bang Core"
  version: 2.1.0
  url: https://p1.dso.mil/products/big-bang
  architecture: amd64

variables:
  - name: DOMAIN
    default: "bigbang.dev"
    prompt: false

components:
  - name: bigbang
    required: true
    extensions:
      bigbang:
        version: 2.1.0
        valuesFiles:
          - ../../../../chart/ingress-certs.yaml
          - ../../../../chart/values.yaml
  - name: gitea-virtual-service
    description: >
      Expose the internal Zarf Gitea server through the Big Bang Istio deployment via a virtual service.
      (only applies if you are using the Zarf-provided Gitea deployment - not an externally configured git host)
    manifests:
      - name: gitea
        namespace: zarf
        files:
          - virtualservices/gitea.yaml
