{{- if and (not .Values.offline) .Values.clusterAuditor.enabled }}
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: cluster-auditor
  namespace: {{ .Release.Namespace }}
spec:
  interval: {{ .Values.flux.interval }}
  url: {{ .Values.clusterAuditor.git.repo }}
  ref:
    {{- include "validRef" .Values.clusterAuditor.git | nindent 4 }}
  {{ include "gitIgnore" . }}
{{- end }}
