{{- if .Values.zalandoPostgresOperator.enabled }}
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: zalando-postgres-operator
  namespace: {{ .Release.Namespace }}
spec:
  targetNamespace: postgres-operator
  chart:
    spec:
      chart: {{ .Values.zalandoPostgresOperator.git.path }}
      interval: 5m
      sourceRef:
        kind: GitRepository
        name: zalando-postgres-operator
        namespace: {{ .Release.Namespace }}

  {{- with .Values.flux }}
  interval: {{ .interval }}
  test:
    enable: false
  install:
    remediation:
      retries: {{ .install.retries }}
  upgrade:
    remediation:
      retries: {{ .upgrade.retries }}
      remediateLastFailure: true
    cleanupOnFail: true
  rollback:
    timeout: {{ .rollback.timeout }}
    cleanupOnFail: {{ .rollback.cleanupOnFail }}
  {{- end }}

  valuesFrom:
  - name: values
    kind: Secret
    valuesKey: "zalando-postgres-operator.yaml"

  values: {}

  # TODO: DRY this up
  {{- if or .Values.gatekeeper.enabled .Values.istio.enabled }}
  dependsOn:
    {{- if .Values.gatekeeper.enabled }}
    - name: gatekeeper
      namespace: {{ .Release.Namespace }}
    {{- end }}
    {{- if .Values.istio.enabled }}
    - name: istio
      namespace: {{ .Release.Namespace }}
    {{- end }}
    {{- if .Values.monitoring.enabled }}
    - name: monitoring
      namespace: {{ .Release.Namespace }}
    {{- end }}
  {{- end }}
{{- end }}