apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: helloworld
  namespace: {{ .Release.Namespace }}
spec:
  interval: {{ .Values.flux.interval }}
  url: {{ .Values.helloworld.git.repo }}
  ref:
    {{- include "validRef" .Values.helloworld.git | nindent 4 }}
  {{ include "gitIgnore" . }}
  {{- include "gitCreds" .Values.git | nindent 2 }}